Grant cloud build service account permissions
In preparation for moving the `docker` commands in `test/e2e/build.sh` to Cloud Build. Currently, a build errors with 

```
AccessDeniedException: 403 735463103342@cloudbuild.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.
```

https://cloud.google.com/cloud-build/docs/cloud-build-service-account#default_permissions_of_service_account outlines the required permissions.